project:
  type: website
  output-dir: _site

website:
  title: "BEAR"
  site-url: "https://wwiecek.github.io/BEAR/"
  repo-url: "https://github.com/wwiecek/BEAR"
  repo-actions: [source, issue]
  favicon: assets/favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: getting-started.qmd
        text: Get data
      - href: datasets.qmd
        text: Datasets
      - href: documentation.qmd
        text: Documentation
      - href: selection.qmd
        text: Selection
      - href: reproduce.qmd
        text: Reproduce
    right:
      - icon: github
        href: https://github.com/wwiecek/BEAR
        aria-label: GitHub repository
  sidebar:
    - title: "Datasets"
      style: docked
      contents:
        - datasets.qmd
        - section: "Dataset pages"
          contents: datasets/*.qmd

bibliography: ../doc/references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    fig-align: center
    link-external-newwindow: true
