## Arel-Bundock et al 2022 (political science)

**Reference:**
@arel2022quantitative.

**Research question:**
assess statistical power in political science research

**Data availability:**
The replication package (a zip file dated `20241010`) is available at
<https://osf.io/fgdet>. All data are in the public domain.

**Data description and source:**
The authors searched for meta-analytic articles across 141 journals in
political science and contacted their authors. The resulting source dataset contains 16,649
hypothesis tests, grouped in 351 meta-analyses and reported in 46 peer-reviewed
meta-analytic articles. 

**Notes:**
This dataset collects meta-analysis inputs, rather than repeating data extraction
from individual studies. It combines an earlier dataset from Doucouliagos et al with
another search. Therefore, some of this dataset will overlap with Askarov et al.
However, the two articles aim to cover different fields and BEAR keeps the two
datasets separate.

**Data processing:**
We used the same code as the original authors (a replication package that uses
makefiles), but skipped some additional processing they performed for their paper.
BEAR uses `question_id` as `metaid` (351 groups defined by meta-analysis or research question).
Signed z-values were
computed as reported estimates divided by their standard errors. We verified
that the distributions of z-values matched those in the article.

**Study characteristics:**

- **Study ID:** we use author's study ID; for **meta-analysis ID** we use `question_id`.
- `subset` is the source article's `meta_id`; each article may contain several
  groupings into meta-analyses 
- `topic` uses the column `subfield` from original dataset (American Politics, 
  Comparative Politics, International Relations, Public Administration, and 
  Political Economy).
- `topic_detailed` is assigned by us, but available only in `data/ArelBundock.rds` 
  it has more detailed classification into topics (instead of subfields) of 
  research.
- `doi_collection` identifies the source publication containing a given collection
  of meta-analyses. It is NOT the indvidual study DOI, nor the meta-analysis DOI.
- `doi_study` is the individual paper DOI, reconstructed by matching labels within
  the dataset to bibliographies in 46 datasets and cross-referencing them. 
  However, it is only available for a minority of studies.
- We do not have information on the study design or measure of effect size.

There are at least several other useful columns in the original replication 
package, which are included in `ArelBundock.rds` without any modifications. 
In particular, `overall_effect` and `subset`, `iv` and `dv` carry a lot of 
information about what is being estimated. 
