## What Works Clearinghouse (education)

Large database of education effect sizes created by the Institute of Education Sciences [@wwc2025studyfindings].

**Snapshot date:**
17 May 2025

**Data availability:**
Flat files are available at <https://ies.ed.gov/ncee/wwc/studyfindings>. The 
Permissions and Disclaimers section of that website states: "Unless stated 
otherwise, all information on the U.S. Department of Education's IES website ... 
is in the public domain and may be reproduced, published, linked to, or otherwise 
used without permission from IES."

**Data collection:**
The WWC source data have 13,054 findings (data rows) across 1,908 reviews.
Each row is one finding, so a single source paper can contribute multiple rows.
The dataset includes effect sizes, but not standard errors, as well as p-values
reported by the studies and p-values re-calculated by the WWC reviewers. After
BEAR processing and filtering, the main BEAR dataset includes 7,080 findings.

**Data processing:**
We include only RCTs and quasi-experimental studies (98% of data altogether).
Majority of these (about 80%) are RCTs.

We removed a few rows where the results were flagged as not meeting WWC
standards or as ineligible for review.
We also removed rows marked by WWC as subgroup measures to avoid treating
subgroup analyses as independent focal findings.
Where available, we preferred effect sizes and p-values calculated by WWC to
the ones reported by the studies. We replaced p-values that were equal to zero
(this occurred in 3% of the dataset) with a truncated p-value (i.e. assumed
$p < 10^{-16}$). We calculated z-values from these p-values under the assumption of
two-sided tests. We then applied the sign of the reported effect size, so
z-values are signed where the effect size is non-zero.

**Study characteristics:**

- **Study ID:** we use citation-derived author and year; we use the original 
  `WWCStudy` as fall-back in some cases.
- **Topic:** WWC dataset includes some useful topic classifications, but these 
  are not included in `BEAR.rds` as they are either too granular or are overlapping 
  flags for study categories
